---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raw-ip-onedns-ch
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: raw-ip-onedns-ch
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: raw-ip-onedns-ch
    spec:
      containers:
      - image: pablo06/iplookup-api:v1.0.0-redirect
        imagePullPolicy: Always
        name: raw-ip-onedns-ch
        resources:
          requests:
            cpu: "20m"
            memory: "20M"
          limits:
            cpu: "40m"
            memory: "30M"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name:  raw-ip-onedns-ch-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: raw-ip-onedns-ch
  minReplicas: 5
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: raw-ip-onedns-ch-svc
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: raw-ip-onedns-ch
